on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:
name: 🚀 Compile & Deploy website on push to production
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code of the action
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run release
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.strato.com
        username: ${{ secrets.USERNAME }}
        local-dir: "./dist/"
        server-dir: "./writingdowngoodreasons-staging/"
        password: ${{ secrets.PASSWORD }}
